#!/bin/bash

sudo apt update
sudo apt install libgmp-dev libmpfr-dev
sudo apt install texinfo
sudo apt install bison
sudo apt install m4

BUILD_PATH="~/ttex/ttex_implementation/build"
git clone --depth 1 git://sourceware.org/git/binutils-gdb.git binutils

if [ -d "$BUILD_PATH" ]; then
    cd "$BUILD_PATH"
else
    mkdir -p "$BUILD_PATH"
    cd "$BUILD_PATH"
fi

#-DLLVM_ENABLE_RUNTIMES="libc;libcxx;libcxxabi;libunwind"
CC='gcc' CXX='g++' cmake -DCMAKE_BUILD_TYPE=Release -DLLVM_USE_LINKER=gold  -DLLVM_BINUTILS_INCDIR=../binutils/include -DLLVM_ENABLE_PROJECTS="clang;lld;openmp" DLIBOMP_OMPT_OPTIONAL=ON DLIBIOMP_OMPT_SUPPORT=ON DLIBOMP_USE_DEBUGGER=ON -G "Ninja" ../llvm
sudo ninja -j4
make all-gold
