#!/bin/bash

BUILD_PATH="/home/swastik/dev/realtimesys/ttex/llvm-project/build"

if [ -d "$BUILD_PATH" ]; then
    cd "$BUILD_PATH"
else
    mkdir -p "$BUILD_PATH"
    cd "$BUILD_PATH"
fi

#-DLLVM_ENABLE_RUNTIMES="libc;libcxx;libcxxabi;libunwind"

CC='gcc' CXX='g++' cmake -DCMAKE_BUILD_TYPE=Debug -DLLVM_USE_LINKER=gold -DLLVM_ENABLE_PROJECTS="clang;lld;openmp" DLIBOMP_OMPT_OPTIONAL=ON DLIBIOMP_OMPT_SUPPORT=ON DLIBOMP_USE_DEBUGGER=ON -G "Ninja" ../llvm

sudo ninja -j4
